theme: jekyll-theme-hacker
name: "Mahmoud Elshenhab"
title: "Mahmoud Elshenhab CV"
author: "Mahmoud Elshenhab"
email: "root@gurutux.com"
description: > "I am a linux System Engineer, working for AWS. I love automation and this is why I am moving from my current role as a Cloud Support Engineer to a System Engineer in the network automation team in AWS."

# social links
twitter_username: "gurutux"
github_username:  "gurutux"
rss: rss
# dribbble_username: jekyll
facebook_username: "mahmoud.alshinhab"
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: "mahmoudalshinhab"
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll
show_excerpts: false # set to true to show excerpts on the homepage
