title: Mahmoud Elshenhab CV
description: I have decided to migrate my PDF CV into HTML CV so I can keep everyone updated with the latest update.
show_downloads: false
#google_analytics:
theme: jekyll-theme-hacker
